services:
    - docker

if: branch = master

before_install:
    - cp .env.example .env

script:
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker-compose exec server python manage.py migrate

after_script:
    - docker-compose ps
