services:
    - docker

if: branch = master

before_install:
    - cp .env.example .env

script:
    - docker-compose build --no-cache
    - docker-compose up -d
    - make postbuild
    - make loaddata

after_script:
    - docker-compose ps
