version: '3'

services:
    server:
        build: ./server
        restart: unless-stopped
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./server/:/server/
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:1.19.0-alpine
        restart: unless-stopped
        ports:
            - ${PORT_WEB}:80
        volumes:
            - ./nginx/triprating.conf:/etc/nginx/conf.d/default.conf
            - ./server/static/:/server/static/
        depends_on:
            - server

    redis:
        image: redis
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - ${PORT_REDIS}:6379

    db:
        image: postgres
        restart: always
        ports:
            - ${PORT_DB}:5432
        env_file:
            - .env
